"""IEEE-style reference strings, keyed as in docs/paper/references.bib where the
work also appears there. Only works the author is confident exist are listed;
volume/page data should still be checked against publisher records before
submission (as references.bib itself notes)."""

REFS = {
    # ---- from docs/paper/references.bib -----------------------------------
    "liao2020db": 'M. Liao, Z. Wan, C. Yao, K. Chen, and X. Bai, "Real-time scene text detection with differentiable binarization," in *Proc. AAAI Conf. Artificial Intelligence*, vol. 34, no. 07, 2020, pp. 11474–11481.',
    "shi2017crnn": 'B. Shi, X. Bai, and C. Yao, "An end-to-end trainable neural network for image-based sequence recognition and its application to scene text recognition," *IEEE Trans. Pattern Anal. Mach. Intell.*, vol. 39, no. 11, pp. 2298–2304, 2017.',
    "graves2006ctc": 'A. Graves, S. Fernández, F. Gomez, and J. Schmidhuber, "Connectionist temporal classification: Labelling unsegmented sequence data with recurrent neural networks," in *Proc. 23rd Int. Conf. Machine Learning (ICML)*, 2006, pp. 369–376.',
    "du2020ppocr": 'Y. Du, C. Li, R. Guo, X. Yin, W. Liu, J. Zhou, Y. Bai, Z. Yu, Y. Yang, Q. Dang, and H. Wang, "PP-OCR: A practical ultra lightweight OCR system," arXiv:2009.09941, 2020.',
    "li2022ppocrv3": 'C. Li, W. Liu, R. Guo, X. Yin, K. Jiang, Y. Du, Y. Du, L. Zhu, B. Lai, X. Hu, D. Yu, and Y. Ma, "PP-OCRv3: More attempts for the improvement of ultra lightweight OCR system," arXiv:2206.03001, 2022.',
    "paddleocr": 'PaddlePaddle Authors, "PaddleOCR: Awesome multilingual OCR toolkits based on PaddlePaddle." [Online]. Available: https://github.com/PaddlePaddle/PaddleOCR (accessed 2026).',
    "howard2019mobilenetv3": 'A. Howard, M. Sandler, G. Chu, L.-C. Chen, B. Chen, M. Tan, W. Wang, Y. Zhu, R. Pang, V. Vasudevan, Q. V. Le, and H. Adam, "Searching for MobileNetV3," in *Proc. IEEE/CVF Int. Conf. Computer Vision (ICCV)*, 2019, pp. 1314–1324.',
    "tiedemann2020opusmt": 'J. Tiedemann and S. Thottingal, "OPUS-MT – Building open translation services for the world," in *Proc. 22nd Annu. Conf. European Association for Machine Translation (EAMT)*, 2020, pp. 479–480.',
    "junczys2018marian": 'M. Junczys-Dowmunt, R. Grundkiewicz, T. Dwojak, H. Hoang, K. Heafield, T. Neckermann, F. Seide, U. Germann, A. F. Aji, N. Bogoychev, A. F. T. Martins, and A. Birch, "Marian: Fast neural machine translation in C++," in *Proc. ACL 2018, System Demonstrations*, 2018, pp. 116–121.',
    "vaswani2017attention": 'A. Vaswani, N. Shazeer, N. Parmar, J. Uszkoreit, L. Jones, A. N. Gomez, Ł. Kaiser, and I. Polosukhin, "Attention is all you need," in *Advances in Neural Information Processing Systems (NeurIPS)*, vol. 30, 2017.',
    "kudo2018sentencepiece": 'T. Kudo and J. Richardson, "SentencePiece: A simple and language independent subword tokenizer and detokenizer for neural text processing," in *Proc. EMNLP 2018: System Demonstrations*, 2018, pp. 66–71.',
    "kudo2018unigram": 'T. Kudo, "Subword regularization: Improving neural network translation models with multiple subword candidates," in *Proc. 56th Annu. Meeting Assoc. Computational Linguistics (ACL)*, 2018, pp. 66–75.',
    "utiyama2007pivot": 'M. Utiyama and H. Isahara, "A comparison of pivot methods for phrase-based statistical machine translation," in *Proc. NAACL-HLT*, 2007, pp. 484–491.',
    "nllb2022": 'NLLB Team, M. R. Costa-jussà *et al.*, "No language left behind: Scaling human-centered machine translation," arXiv:2207.04672, 2022.',
    "jacob2018quant": 'B. Jacob, S. Kligys, B. Chen, M. Zhu, M. Tang, A. Howard, H. Adam, and D. Kalenichenko, "Quantization and training of neural networks for efficient integer-arithmetic-only inference," in *Proc. IEEE Conf. Computer Vision and Pattern Recognition (CVPR)*, 2018, pp. 2704–2713.',
    "onnxruntime": 'ONNX Runtime developers, "ONNX Runtime." [Online]. Available: https://onnxruntime.ai (accessed 2026).',
    "andrew1979hull": 'A. M. Andrew, "Another efficient algorithm for convex hulls in two dimensions," *Information Processing Letters*, vol. 9, no. 5, pp. 216–219, 1979.',
    "freeman1975rect": 'H. Freeman and R. Shapira, "Determining the minimum-area encasing rectangle for an arbitrary closed curve," *Commun. ACM*, vol. 18, no. 7, pp. 409–413, 1975.',
    "toussaint1983calipers": 'G. T. Toussaint, "Solving geometric problems with the rotating calipers," in *Proc. IEEE MELECON \'83*, 1983.',
    "vatti1992clip": 'B. R. Vatti, "A generic solution to polygon clipping," *Commun. ACM*, vol. 35, no. 7, pp. 56–63, 1992.',
    "knuth1981breaking": 'D. E. Knuth and M. F. Plass, "Breaking paragraphs into lines," *Software: Practice and Experience*, vol. 11, no. 11, pp. 1119–1184, 1981.',
    "telea2004inpaint": 'A. Telea, "An image inpainting technique based on the fast marching method," *J. Graphics Tools*, vol. 9, no. 1, pp. 23–34, 2004.',
    "suvorov2022lama": 'R. Suvorov, E. Logacheva, A. Mashikhin, A. Remizova, A. Ashukha, A. Silvestrov, N. Kong, H. Goka, K. Park, and V. Lempitsky, "Resolution-robust large mask inpainting with Fourier convolutions," in *Proc. IEEE/CVF Winter Conf. Applications of Computer Vision (WACV)*, 2022, pp. 2149–2159.',
    "zhang2019ensnet": 'S. Zhang, Y. Liu, L. Jin, Y. Huang, and S. Lai, "EnsNet: Ensconce text in the wild," in *Proc. AAAI Conf. Artificial Intelligence*, vol. 33, 2019, pp. 801–808.',
    "wu2019srnet": 'L. Wu, C. Zhang, J. Liu, J. Han, J. Liu, E. Ding, and X. Bai, "Editing text in the wild," in *Proc. 27th ACM Int. Conf. Multimedia*, 2019, pp. 1500–1508.',
    "roy2020stefann": 'P. Roy, S. Bhattacharya, S. Ghosh, and U. Pal, "STEFANN: Scene text editor using font adaptive neural network," in *Proc. IEEE/CVF Conf. Computer Vision and Pattern Recognition (CVPR)*, 2020, pp. 13228–13237.',
    "mansimov2020inimage": 'E. Mansimov, M. Stern, M. Chen, O. Firat, J. Uszkoreit, and P. Jain, "Towards end-to-end in-image neural machine translation," in *Proc. First Int. Workshop on Natural Language Processing Beyond Text*, 2020, pp. 70–74.',
    "karatzas2015icdar": 'D. Karatzas, L. Gomez-Bigorda, A. Nicolaou, S. Ghosh, A. Bagdanov, M. Iwamura, J. Matas, L. Neumann, V. R. Chandrasekhar, S. Lu, F. Shafait, S. Uchida, and E. Valveny, "ICDAR 2015 competition on robust reading," in *Proc. 13th Int. Conf. Document Analysis and Recognition (ICDAR)*, 2015, pp. 1156–1160.',
    "nayef2019mlt": 'N. Nayef, Y. Patel, M. Busta, P. N. Chowdhury, D. Karatzas, W. Khlif, J. Matas, U. Pal, J.-C. Burie, C.-L. Liu, and J.-M. Ogier, "ICDAR2019 robust reading challenge on multi-lingual scene text detection and recognition – RRC-MLT-2019," in *Proc. 15th Int. Conf. Document Analysis and Recognition (ICDAR)*, 2019, pp. 1582–1587.',
    "papineni2002bleu": 'K. Papineni, S. Roukos, T. Ward, and W.-J. Zhu, "BLEU: A method for automatic evaluation of machine translation," in *Proc. 40th Annu. Meeting Assoc. Computational Linguistics (ACL)*, 2002, pp. 311–318.',
    "popovic2015chrf": 'M. Popović, "chrF: Character n-gram F-score for automatic MT evaluation," in *Proc. Tenth Workshop on Statistical Machine Translation (WMT)*, 2015, pp. 392–395.',
    "post2018sacrebleu": 'M. Post, "A call for clarity in reporting BLEU scores," in *Proc. Third Conf. Machine Translation (WMT)*, 2018, pp. 186–191.',
    "rei2020comet": 'R. Rei, C. Stewart, A. C. Farinha, and A. Lavie, "COMET: A neural framework for MT evaluation," in *Proc. 2020 Conf. Empirical Methods in Natural Language Processing (EMNLP)*, 2020, pp. 2685–2702.',
    "wcag21": 'World Wide Web Consortium, "Web Content Accessibility Guidelines (WCAG) 2.1," W3C Recommendation, 2018. [Online]. Available: https://www.w3.org/TR/WCAG21/',
    "porter1984compositing": 'T. Porter and T. Duff, "Compositing digital images," *ACM SIGGRAPH Computer Graphics*, vol. 18, no. 3, pp. 253–259, 1984.',
    # ---- additional works -------------------------------------------------
    "smith2007tesseract": 'R. Smith, "An overview of the Tesseract OCR engine," in *Proc. 9th Int. Conf. Document Analysis and Recognition (ICDAR)*, 2007, pp. 629–633.',
    "long2021survey": 'S. Long, X. He, and C. Yao, "Scene text detection and recognition: The deep learning era," *Int. J. Computer Vision*, vol. 129, no. 1, pp. 161–184, 2021.',
    "zhou2017east": 'X. Zhou, C. Yao, H. Wen, Y. Wang, S. Zhou, W. He, and J. Liang, "EAST: An efficient and accurate scene text detector," in *Proc. IEEE Conf. Computer Vision and Pattern Recognition (CVPR)*, 2017, pp. 5551–5560.',
    "tian2016ctpn": 'Z. Tian, W. Huang, T. He, P. He, and Y. Qiao, "Detecting text in natural image with connectionist text proposal network," in *Proc. European Conf. Computer Vision (ECCV)*, 2016, pp. 56–72.',
    "baek2019craft": 'Y. Baek, B. Lee, D. Han, S. Yun, and H. Lee, "Character region awareness for text detection," in *Proc. IEEE/CVF Conf. Computer Vision and Pattern Recognition (CVPR)*, 2019, pp. 9365–9374.',
    "wang2019psenet": 'W. Wang, E. Xie, X. Li, W. Hou, T. Lu, G. Yu, and S. Shao, "Shape robust text detection with progressive scale expansion network," in *Proc. IEEE/CVF Conf. Computer Vision and Pattern Recognition (CVPR)*, 2019, pp. 9336–9345.',
    "liao2023dbpp": 'M. Liao, Z. Zou, Z. Wan, C. Yao, and X. Bai, "Real-time scene text detection with differentiable binarization and adaptive scale fusion," *IEEE Trans. Pattern Anal. Mach. Intell.*, vol. 45, no. 1, pp. 919–931, 2023.',
    "shi2019aster": 'B. Shi, M. Yang, X. Wang, P. Lyu, C. Yao, and X. Bai, "ASTER: An attentional scene text recognizer with flexible rectification," *IEEE Trans. Pattern Anal. Mach. Intell.*, vol. 41, no. 9, pp. 2035–2048, 2019.',
    "baek2019wrong": 'J. Baek, G. Kim, J. Lee, S. Park, D. Han, S. Yun, S. J. Oh, and H. Lee, "What is wrong with scene text recognition model comparisons? Dataset and model analysis," in *Proc. IEEE/CVF Int. Conf. Computer Vision (ICCV)*, 2019, pp. 4715–4723.',
    "hochreiter1997lstm": 'S. Hochreiter and J. Schmidhuber, "Long short-term memory," *Neural Computation*, vol. 9, no. 8, pp. 1735–1780, 1997.',
    "jaderberg2016reading": 'M. Jaderberg, K. Simonyan, A. Vedaldi, and A. Zisserman, "Reading text in the wild with convolutional neural networks," *Int. J. Computer Vision*, vol. 116, no. 1, pp. 1–20, 2016.',
    "gupta2016synthtext": 'A. Gupta, A. Vedaldi, and A. Zisserman, "Synthetic data for text localisation in natural images," in *Proc. IEEE Conf. Computer Vision and Pattern Recognition (CVPR)*, 2016, pp. 2315–2324.',
    "sandler2018mobilenetv2": 'M. Sandler, A. Howard, M. Zhu, A. Zhmoginov, and L.-C. Chen, "MobileNetV2: Inverted residuals and linear bottlenecks," in *Proc. IEEE Conf. Computer Vision and Pattern Recognition (CVPR)*, 2018, pp. 4510–4520.',
    "sutskever2014seq2seq": 'I. Sutskever, O. Vinyals, and Q. V. Le, "Sequence to sequence learning with neural networks," in *Advances in Neural Information Processing Systems (NeurIPS)*, vol. 27, 2014.',
    "bahdanau2015attention": 'D. Bahdanau, K. Cho, and Y. Bengio, "Neural machine translation by jointly learning to align and translate," in *Proc. Int. Conf. Learning Representations (ICLR)*, 2015.',
    "wu2016gnmt": 'Y. Wu *et al.*, "Google\'s neural machine translation system: Bridging the gap between human and machine translation," arXiv:1609.08144, 2016.',
    "sennrich2016bpe": 'R. Sennrich, B. Haddow, and A. Birch, "Neural machine translation of rare words with subword units," in *Proc. 54th Annu. Meeting Assoc. Computational Linguistics (ACL)*, 2016, pp. 1715–1725.',
    "tiedemann2012opus": 'J. Tiedemann, "Parallel data, tools and interfaces in OPUS," in *Proc. 8th Int. Conf. Language Resources and Evaluation (LREC)*, 2012, pp. 2214–2218.',
    "johnson2017multilingual": 'M. Johnson *et al.*, "Google\'s multilingual neural machine translation system: Enabling zero-shot translation," *Trans. Assoc. Computational Linguistics*, vol. 5, pp. 339–351, 2017.',
    "firat2016multiway": 'O. Firat, K. Cho, and Y. Bengio, "Multi-way, multilingual neural machine translation with a shared attention mechanism," in *Proc. NAACL-HLT*, 2016, pp. 866–875.',
    "fan2021m2m": 'A. Fan *et al.*, "Beyond English-centric multilingual machine translation," *J. Machine Learning Research*, vol. 22, no. 107, pp. 1–48, 2021.',
    "wu2007pivot": 'H. Wu and H. Wang, "Pivot language approach for phrase-based statistical machine translation," *Machine Translation*, vol. 21, no. 3, pp. 165–181, 2007.',
    "goyal2022flores": 'N. Goyal, C. Gao, V. Chaudhary, P.-J. Chen, G. Wenzek, D. Ju, S. Krishnan, M. Ranzato, F. Guzmán, and A. Fan, "The Flores-101 evaluation benchmark for low-resource and multilingual machine translation," *Trans. Assoc. Computational Linguistics*, vol. 10, pp. 522–538, 2022.',
    "kim2016distill": 'Y. Kim and A. M. Rush, "Sequence-level knowledge distillation," in *Proc. 2016 Conf. Empirical Methods in Natural Language Processing (EMNLP)*, 2016, pp. 1317–1327.',
    "hinton2015distill": 'G. Hinton, O. Vinyals, and J. Dean, "Distilling the knowledge in a neural network," arXiv:1503.02531, 2015.',
    "kim2019ludicrous": 'Y. J. Kim, M. Junczys-Dowmunt, H. Hassan, A. F. Aji, K. Heafield, R. Grundkiewicz, and N. Bogoychev, "From research to production and back: Ludicrously fast neural machine translation," in *Proc. 3rd Workshop on Neural Generation and Translation (WNGT)*, 2019, pp. 280–288.',
    "kasai2021deepshallow": 'J. Kasai, N. Pappas, H. Peng, J. Cross, and N. A. Smith, "Deep encoder, shallow decoder: Reevaluating non-autoregressive machine translation," in *Proc. Int. Conf. Learning Representations (ICLR)*, 2021.',
    "krishnamoorthi2018quant": 'R. Krishnamoorthi, "Quantizing deep convolutional networks for efficient inference: A whitepaper," arXiv:1806.08342, 2018.',
    "bhandare2019int8nmt": 'A. Bhandare, V. Sripathi, D. Karkada, V. Menon, S. Choi, K. Datta, and V. Saletore, "Efficient 8-bit quantization of transformer neural machine language translation model," arXiv:1906.00532, 2019.',
    "han2016deepcompression": 'S. Han, H. Mao, and W. J. Dally, "Deep compression: Compressing deep neural networks with pruning, trained quantization and Huffman coding," in *Proc. Int. Conf. Learning Representations (ICLR)*, 2016.',
    "pope2023scaling": 'R. Pope, S. Douglas, A. Chowdhery, J. Devlin, J. Bradbury, J. Heek, K. Xiao, S. Agrawal, and J. Dean, "Efficiently scaling transformer inference," in *Proc. Machine Learning and Systems (MLSys)*, vol. 5, 2023.',
    "wolf2020transformers": 'T. Wolf *et al.*, "Transformers: State-of-the-art natural language processing," in *Proc. 2020 Conf. Empirical Methods in Natural Language Processing: System Demonstrations*, 2020, pp. 38–45.',
    "abadi2016tensorflow": 'M. Abadi *et al.*, "TensorFlow: A system for large-scale machine learning," in *Proc. 12th USENIX Symp. Operating Systems Design and Implementation (OSDI)*, 2016, pp. 265–283.',
    "jiang2020mnn": 'X. Jiang *et al.*, "MNN: A universal and efficient inference engine," in *Proc. Machine Learning and Systems (MLSys)*, vol. 2, 2020.',
    "ignatov2018aibench": 'A. Ignatov, R. Timofte, W. Chou, K. Wang, M. Wu, T. Hartley, and L. Van Gool, "AI Benchmark: Running deep neural networks on Android smartphones," in *Proc. European Conf. Computer Vision (ECCV) Workshops*, 2018.',
    "onnx": 'ONNX Community, "Open Neural Network Exchange (ONNX)." [Online]. Available: https://onnx.ai (accessed 2026).',
    "paddle2onnx": 'PaddlePaddle Authors, "Paddle2ONNX." [Online]. Available: https://github.com/PaddlePaddle/Paddle2ONNX (accessed 2026).',
    "optimum": 'Hugging Face, "Optimum: Accelerate training and inference of Transformers." [Online]. Available: https://github.com/huggingface/optimum (accessed 2026).',
    "bradski2000opencv": 'G. Bradski, "The OpenCV library," *Dr. Dobb\'s Journal of Software Tools*, 2000.',
    "suzuki1985border": 'S. Suzuki and K. Abe, "Topological structural analysis of digitized binary images by border following," *Computer Vision, Graphics, and Image Processing*, vol. 30, no. 1, pp. 32–46, 1985.',
    "graham1972hull": 'R. L. Graham, "An efficient algorithm for determining the convex hull of a finite planar set," *Information Processing Letters*, vol. 1, no. 4, pp. 132–133, 1972.',
    "deberg2008cg": 'M. de Berg, O. Cheong, M. van Kreveld, and M. Overmars, *Computational Geometry: Algorithms and Applications*, 3rd ed. Berlin, Germany: Springer, 2008.',
    "preparata1985cg": 'F. P. Preparata and M. I. Shamos, *Computational Geometry: An Introduction*. New York, NY, USA: Springer, 1985.',
    "hartley2004mvg": 'R. Hartley and A. Zisserman, *Multiple View Geometry in Computer Vision*, 2nd ed. Cambridge, U.K.: Cambridge Univ. Press, 2004.',
    "forney1973viterbi": 'G. D. Forney, "The Viterbi algorithm," *Proc. IEEE*, vol. 61, no. 3, pp. 268–278, 1973.',
    "levenshtein1966": 'V. I. Levenshtein, "Binary codes capable of correcting deletions, insertions, and reversals," *Soviet Physics Doklady*, vol. 10, no. 8, pp. 707–710, 1966.',
    "bertalmio2000inpainting": 'M. Bertalmio, G. Sapiro, V. Caselles, and C. Ballester, "Image inpainting," in *Proc. 27th Annu. Conf. Computer Graphics and Interactive Techniques (SIGGRAPH)*, 2000, pp. 417–424.',
    "criminisi2004exemplar": 'A. Criminisi, P. Pérez, and K. Toyama, "Region filling and object removal by exemplar-based image inpainting," *IEEE Trans. Image Processing*, vol. 13, no. 9, pp. 1200–1212, 2004.',
    "nakamura2017eraser": 'T. Nakamura, A. Zhu, K. Yanai, and S. Uchida, "Scene text eraser," in *Proc. 14th IAPR Int. Conf. Document Analysis and Recognition (ICDAR)*, 2017, pp. 832–837.',
    "srgb": 'International Electrotechnical Commission, *IEC 61966-2-1:1999, Multimedia systems and equipment – Colour measurement and management – Part 2-1: Colour management – Default RGB colour space – sRGB*, 1999.',
    "bt601": 'International Telecommunication Union, *Recommendation ITU-R BT.601: Studio encoding parameters of digital television for standard 4:3 and wide-screen 16:9 aspect ratios*.',
    "wang2004ssim": 'Z. Wang, A. C. Bovik, H. R. Sheikh, and E. P. Simoncelli, "Image quality assessment: From error visibility to structural similarity," *IEEE Trans. Image Processing*, vol. 13, no. 4, pp. 600–612, 2004.',
    "fitts1954": 'P. M. Fitts, "The information capacity of the human motor system in controlling the amplitude of movement," *J. Experimental Psychology*, vol. 47, no. 6, pp. 381–391, 1954.',
    "parhi2006target": 'P. Parhi, A. K. Karlson, and B. B. Bederson, "Target size study for one-handed thumb use on small touchscreen devices," in *Proc. 8th Conf. Human-Computer Interaction with Mobile Devices and Services (MobileHCI)*, 2006, pp. 203–210.',
    "android_a11y": 'Android Developers, "Make apps more accessible." [Online]. Available: https://developer.android.com/guide/topics/ui/accessibility/apps (accessed 2026).',
    "material_rail": 'Google, "Material Design 3: Navigation rail." [Online]. Available: https://m3.material.io/components/navigation-rail (accessed 2026).',
    "android_memory": 'Android Developers, "Overview of memory management." [Online]. Available: https://developer.android.com/topic/performance/memory-overview (accessed 2026).',
    "brooke1996sus": 'J. Brooke, "SUS: A \'quick and dirty\' usability scale," in *Usability Evaluation in Industry*, P. W. Jordan, B. Thomas, B. A. Weerdmeester, and I. L. McClelland, Eds. London, U.K.: Taylor & Francis, 1996, pp. 189–194.',
    "bates2015lme4": 'D. Bates, M. Mächler, B. Bolker, and S. Walker, "Fitting linear mixed-effects models using lme4," *J. Statistical Software*, vol. 67, no. 1, pp. 1–48, 2015.',
    "baayen2008mixed": 'R. H. Baayen, D. J. Davidson, and D. M. Bates, "Mixed-effects modeling with crossed random effects for subjects and items," *J. Memory and Language*, vol. 59, no. 4, pp. 390–412, 2008.',
    "barr2013maximal": 'D. J. Barr, R. Levy, C. Scheepers, and H. J. Tily, "Random effects structure for confirmatory hypothesis testing: Keep it maximal," *J. Memory and Language*, vol. 68, no. 3, pp. 255–278, 2013.',
    "agresti2010ordinal": 'A. Agresti, *Analysis of Ordinal Categorical Data*, 2nd ed. Hoboken, NJ, USA: Wiley, 2010.',
    "bradley1952paired": 'R. A. Bradley and M. E. Terry, "Rank analysis of incomplete block designs: I. The method of paired comparisons," *Biometrika*, vol. 39, no. 3/4, pp. 324–345, 1952.',
    "wobbrock2011art": 'J. O. Wobbrock, L. Findlater, D. Gergle, and J. J. Higgins, "The aligned rank transform for nonparametric factorial analyses using only ANOVA procedures," in *Proc. SIGCHI Conf. Human Factors in Computing Systems (CHI)*, 2011, pp. 143–146.',
    "holm1979": 'S. Holm, "A simple sequentially rejective multiple test procedure," *Scandinavian J. Statistics*, vol. 6, no. 2, pp. 65–70, 1979.',
    "koehn2004bootstrap": 'P. Koehn, "Statistical significance tests for machine translation evaluation," in *Proc. 2004 Conf. Empirical Methods in Natural Language Processing (EMNLP)*, 2004, pp. 388–395.',
    "kocmi2021ship": 'T. Kocmi, C. Federmann, R. Grundkiewicz, M. Junczys-Dowmunt, H. Matsushita, and A. Menezes, "To ship or not to ship: An extensive evaluation of automatic metrics for machine translation," in *Proc. Sixth Conf. Machine Translation (WMT)*, 2021, pp. 478–494.',
    "wohlin2012experimentation": 'C. Wohlin, P. Runeson, M. Höst, M. C. Ohlsson, B. Regnell, and A. Wesslén, *Experimentation in Software Engineering*. Berlin, Germany: Springer, 2012.',
    "gdpr2016": 'European Parliament and Council of the European Union, "Regulation (EU) 2016/679 (General Data Protection Regulation)," *Official Journal of the European Union*, L 119, 2016.',
    "schuirmann1987tost": 'D. J. Schuirmann, "A comparison of the two one-sided tests procedure and the power approach for assessing the equivalence of average bioavailability," *J. Pharmacokinetics and Biopharmaceutics*, vol. 15, no. 6, pp. 657–680, 1987.',
    "efron1993bootstrap": 'B. Efron and R. J. Tibshirani, *An Introduction to the Bootstrap*. New York, NY, USA: Chapman & Hall, 1993.',
    "mcnemar1947": 'Q. McNemar, "Note on the sampling error of the difference between correlated proportions or percentages," *Psychometrika*, vol. 12, no. 2, pp. 153–157, 1947.',
}
